name: sigma
description: An open source expense tracker.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  outline_material_icons: ^0.1.1
  flutter:
    sdk: flutter
  firebase_core: ^0.4.3+1
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.1.1
  cached_network_image: ^2.0.0-rc
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: "^0.7.4"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "res/icon/ios_1024.png"
  image_path_android: "res/icon/foreground_1024.png"
  adaptive_icon_background: "res/icon/background_1024.png"
  adaptive_icon_foreground: "res/icon/foreground_1024.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/sigma_letter_br.png
    - res/icon/foreground_1024.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: res/fonts/RobotoCondensed-Regular.ttf
        - asset: res/fonts/RobotoCondensed-Italic.ttf
          style: italic
        - asset: res/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: res/fonts/RobotoCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: res/fonts/RobotoCondensed-LightItalic.ttf
          weight: 300
          style: italic

    - family: LibreCaslonDisplay
      fonts:
        - asset: res/fonts/LibreCaslonDisplay-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
