name: Test and coverage
on: push

jobs:
  build:
    name: Build and create APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test --coverage
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lcov.info
        path: coverage/lcov.info
  
  coverage:
    name: Coverage check
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: lcov.info
        path: coverage/lcov.info
    - name: Parse coverage file
      uses: devmasx/coverage-check-action@v1.1.0
      with:
        type: lcov
        result_path: coverage/lcov.info
        min_coverage: 90
        token: ${{secrets.GITHUB_TOKEN}}
