name: Code coverage check
on: push

jobs:
  coverage:
    name: Coverage check
    runs-on: ubuntu-latest
    steps:
    - uses: devmasx/coverage-check-action@v1.1.0
      with:
        type: lcov
        result_path: coverage/lcov.info
        min_coverage: 90
        token: ${{secrets.GITHUB_TOKEN}}
