name: Test and coverage
on: push

jobs:
  build:
    name: Test, build and create Appbundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Flutter upgrade
      run: flutter upgrade
    - name: Flutter get packages
      run: flutter pub get
    - name: Flutter test
      run: flutter test --coverage
    - name: Flutter build signed appbundle
      env:
        KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
      run: flutter build appbundle --build-number $BUILD_NUMBER
    - name: Parse coverage file
      uses: devmasx/coverage-check-action@v1.1.0
      with:
        type: lcov
        result_path: coverage/lcov.info
        min_coverage: 90
        token: ${{secrets.GITHUB_TOKEN}}

