on:
  push:
    branches: 
      - internal-release

name: Test, build and release APK on Google Play Store (internal branch)
jobs:
  build:
    name: Test, build and create APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Flutter upgrade
      run: flutter upgrade
    - name: Flutter get packages
      run: flutter pub get
    - name: Flutter test
      run: flutter test
    - name: Generate build number
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}
    - name: Print build number
      run: echo "Build number is $BUILD_NUMBER"
    - name: Flutter build signed appbundle
      env:
        KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
      run: flutter build appbundle --release --build-number $BUILD_NUMBER
    - name: Key to file
      env:
        KEY_JSON_CONTENT: ${{secrets.PLAY_STORE_JSON}}
      run: echo $KEY_JSON_CONTENT > private_key.json
    - name: Upload bundle to Play Store (internal channel)
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: private_key.json
        packageName: it.riccardopersello.sigma
        releaseFile: build/app/outputs/bundle/release/app-release.aab
        track: internal
      
